/*
 * Copyright 2022 ByteDance and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * CDP开放接口
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2023-02-10
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SegmentationResp struct {
	AllowDownload bool `json:"allowDownload"`
	CantPublicType string `json:"cantPublicType"`
	Count int64 `json:"count"`
	CreatedAt string `json:"createdAt"`
	CreatedBy string `json:"createdBy"`
	ExportAt string `json:"exportAt"`
	ExportStrategy string `json:"exportStrategy"`
	GroupInf []GroupInfo `json:"groupInf,omitempty"`
	HasPublicBefore bool `json:"hasPublicBefore"`
	HashMethod string `json:"hashMethod,omitempty"`
	Id int32 `json:"id"`
	IdType *IdType `json:"idType"`
	IdTypeName string `json:"idTypeName"`
	IsNewestVersion bool `json:"isNewestVersion"`
	Module string `json:"module,omitempty"`
	Name string `json:"name"`
	OnlineSegStatus bool `json:"onlineSegStatus"`
	OnlineSegSyncStatus string `json:"onlineSegSyncStatus"`
	PDate string `json:"pDate,omitempty"`
	Path string `json:"path,omitempty"`
	Platform string `json:"platform,omitempty"`
	ReportId int64 `json:"reportId,omitempty"`
	SegDep *SegDependency `json:"segDep,omitempty"`
	SegPermission []SegPermission `json:"segPermission,omitempty"`
	SegStatus string `json:"segStatus"`
	SegTaskStatus []SegTaskStatus `json:"segTaskStatus,omitempty"`
	SegType string `json:"segType"`
	SourceResultReady bool `json:"sourceResultReady"`
	SubSegmentations []SegmentationResp `json:"subSegmentations,omitempty"`
	SubjectId int32 `json:"subjectId"`
	UploadType string `json:"uploadType,omitempty"`
	Version int32 `json:"version,omitempty"`
}
