/*
 * Copyright 2022 ByteDance and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * CDP开放接口
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2023-02-10
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type OnlineUserProfileRespWithPrivacy struct {
	Code int64 `json:"code,omitempty"`
	Message string `json:"message,omitempty"`
	Properties map[string]string `json:"properties,omitempty"`
	Tags map[string]string `json:"tags,omitempty"`
	PropertiesMapping map[string]string `json:"propertiesMapping,omitempty"`
	TagsMapping map[string]string `json:"tagsMapping,omitempty"`
}
