/*
 * Copyright 2022 ByteDance and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * CDP开放接口
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2023-02-10
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type LegacySegOpenApiInfoResponse struct {
	// 分群id
	Id int32 `json:"id"`
	// 分群名称
	Name string `json:"name"`
	// 分群创建人
	CreatedBy string `json:"createdBy"`
	// 分群实体类型code
	IdType string `json:"idType"`
	// 分群实体类型名称
	IdTypeName string `json:"idTypeName"`
	Result *LegacySegResult `json:"result"`
	// 分群类型
	SegType string `json:"segType"`
	// 是否开启了在线服务
	AbaseEnabled bool `json:"abaseEnabled,omitempty"`
	Detail *DetailModel `json:"detail,omitempty"`
}
