/*
 * Copyright 2022 ByteDance and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * CDP开放接口
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2023-02-10
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type LegacySegOpenApiResponse struct {
	// 分群id
	Id int32 `json:"id"`
	// 分群名称
	Name string `json:"name"`
	// 分群实体类型code
	IdType string `json:"idType"`
	// 分群实体类型名称
	IdTypeName string `json:"idTypeName"`
	// 主体id
	SubjectId int32 `json:"subjectId"`
	// 分群数量
	Count int64 `json:"count,omitempty"`
	// 分群创建人
	CreatedBy string `json:"createdBy"`
	// 分群离线文件地址
	Path string `json:"path,omitempty"`
	// 分群离线文件导出时间，未就绪时为当前时间戳
	ExportAt string `json:"exportAt"`
	// 分群更新方式
	ExportStrategy string `json:"exportStrategy"`
	// 分群任务状态
	SegStatus string `json:"segStatus"`
	// 分群是否就绪
	SourceResultReady bool `json:"sourceResultReady"`
	// 废弃字段
	CantPublicType string `json:"cantPublicType,omitempty"`
	// 废弃字段
	HasPublicBefore bool `json:"hasPublicBefore,omitempty"`
	// 分群创建时间
	CreatedAt string `json:"createdAt"`
	// 分群在ck中的最新版本号
	Version int32 `json:"version,omitempty"`
	// 分群是否开启了在线服务配置
	OnlineSegStatus bool `json:"onlineSegStatus,omitempty"`
	Pdate string `json:"pdate,omitempty"`
}
