/*
 * Copyright 2022 ByteDance and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * CDP开放接口
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2023-02-10
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type LabelInfo struct {
	// 标签id
	Id int32 `json:"id,omitempty"`
	// 标签名
	Name string `json:"name,omitempty"`
	// 主体id
	SubjectId int32 `json:"subjectId,omitempty"`
	// 项目id
	ProjectId int64 `json:"projectId,omitempty"`
	// 集团id
	OrgId int64 `json:"orgId,omitempty"`
	// 实体类型id
	EntityId int32 `json:"entityId,omitempty"`
	// 实体类型
	EntityType string `json:"entityType,omitempty"`
	// 标签类型
	LabelType string `json:"labelType,omitempty"`
	// 标签值类型(映射后)
	DataType string `json:"dataType,omitempty"`
	// 标签创建人
	Creator string `json:"creator,omitempty"`
	// 标签状态,0-正常,1-已删除
	Status int32 `json:"status,omitempty"`
	// 标签描述
	Desc string `json:"desc,omitempty"`
	// 标签创建时间
	CreateTime string `json:"createTime,omitempty"`
	// 标签更新时间
	UpdateTime string `json:"updateTime,omitempty"`
	// 标签更新方式
	ComputeType string `json:"computeType,omitempty"`
	// 是否为mautag,0-否,1-是
	IsMautag int32 `json:"isMautag,omitempty"`
	// 标签任务id
	TaskId int64 `json:"taskId,omitempty"`
	// 标签在标签数据集中对应的维度指标id
	DimMetId int32 `json:"dimMetId,omitempty"`
	// 标签最近修改人
	Updater string `json:"updater,omitempty"`
	// 标签权限等级,默认L3
	DataSecurityLevel string `json:"dataSecurityLevel,omitempty"`
	// 在线api任务,0未创建,1已创建
	CreateApiTask bool `json:"createApiTask,omitempty"`
	// 标签环境:dev/prod
	Env string `json:"env,omitempty"`
	// 同步状态:0-未同步,1-已同步,2-修改未同步
	SyncStatus int32 `json:"syncStatus,omitempty"`
	// 同步时间
	SyncTime string `json:"syncTime,omitempty"`
	// 该标签对应prod环境的标签id,非多环境/prod应为null
	SyncId int32 `json:"syncId,omitempty"`
	// 标签所在的目录id
	NodeId int32 `json:"nodeId,omitempty"`
	// 标签索引位置
	Index int32 `json:"index,omitempty"`
	// 标签是否可读
	Readable bool `json:"readable,omitempty"`
	// 标签是否被收藏
	IsCollected bool `json:"isCollected,omitempty"`
	// 标签是否是模版标签
	IsTemplateLabel bool `json:"isTemplateLabel,omitempty"`
	// 标签是否成功导入在线服务
	IsOnlineService bool `json:"isOnlineService,omitempty"`
	// 标签更新频率
	RefreshFreqDetails string `json:"refreshFreqDetails,omitempty"`
	// 标签覆盖率
	Coverage string `json:"coverage,omitempty"`
}
