/*
 * Copyright 2022 ByteDance and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * CDP开放接口
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2023-02-10
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"time"
)

type LabelMetaInfo struct {
	Id                        int32        `json:"id,omitempty"`
	Name                      string       `json:"name,omitempty"`
	OrgId                     int64        `json:"orgId,omitempty"`
	ProjectId                 int64        `json:"projectId,omitempty"`
	Descr                     string       `json:"descr,omitempty"`
	DataSecurityLevel         string       `json:"dataSecurityLevel,omitempty"`
	LabelType                 string       `json:"labelType,omitempty"`
	DataTypeName              string       `json:"dataTypeName,omitempty"`
	DomainId                  int32        `json:"domainId,omitempty"`
	Position                  float64      `json:"position,omitempty"`
	EntityId                  int32        `json:"entityId,omitempty"`
	EntityType                string       `json:"entityType,omitempty"`
	ComputeType               string       `json:"computeType,omitempty"`
	IsMautag                  int32        `json:"isMautag,omitempty"`
	SyncParams                *interface{} `json:"syncParams,omitempty"`
	Conf                      *interface{} `json:"conf,omitempty"`
	TaskId                    int32        `json:"taskId,omitempty"`
	DimMetId                  int32        `json:"dimMetId,omitempty"`
	LabelRangeRules           *interface{} `json:"labelRangeRules,omitempty"`
	Status                    int32        `json:"status,omitempty"`
	CreateApiTask             bool         `json:"createApiTask,omitempty"`
	RealtimeTaskId            int32        `json:"realtimeTaskId,omitempty"`
	RealtimeStatus            int32        `json:"realtimeStatus,omitempty"`
	Owner                     string       `json:"owner,omitempty"`
	CreateTime                time.Time    `json:"createTime,omitempty"`
	Updater                   string       `json:"updater,omitempty"`
	UpdateTime                time.Time    `json:"updateTime,omitempty"`
	AbiDimMetId               int32        `json:"abiDimMetId,omitempty"`
	LastSuccessTaskInstanceId int32        `json:"lastSuccessTaskInstanceId,omitempty"`
	LatestRunDate             time.Time    `json:"latestRunDate,omitempty"`
	UserNum                   int32        `json:"userNum,omitempty"`
	Values                    []string     `json:"values,omitempty"`
}
