/*
 * Copyright 2022 ByteDance and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * CDP开放接口
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2023-02-10
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CdpEventVo struct {
	// 事件id
	Id int32 `json:"id,omitempty"`
	// 事件id, 别名
	EventId int32 `json:"eventId,omitempty"`
	// 事件名
	EnName string `json:"enName,omitempty"`
	// 事件展示名
	CnName string `json:"cnName,omitempty"`
	// 事件描述
	Description string `json:"description,omitempty"`
	// 事件类型
	EventType int32 `json:"eventType,omitempty"`
	// 第三方数据源原始id，默认0
	OriginId int32 `json:"originId,omitempty"`
	// 是否显示
	IsDisplay bool `json:"isDisplay,omitempty"`
	// 是否可编辑
	EditBan bool `json:"editBan,omitempty"`
	// 数据源id
	DataSourceId int32 `json:"dataSourceId,omitempty"`
	// 数据源名
	DataSourceName string `json:"dataSourceName,omitempty"`
	// 数据源注册来源
	SourceTag string `json:"sourceTag,omitempty"`
	// 数据源类型
	SourceType int32 `json:"sourceType,omitempty"`
}
