/*
 * Copyright 2022 ByteDance and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * CDP开放接口
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2023-02-10
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// 标签树结点全部信息,部分字段在特定查询case下非null,返回值时为root层级结点List
type LabelTreeNode struct {
	// 结点ID
	Id int32 `json:"id,omitempty"`
	// 当前结点上层结点ID
	PreNodeId int32 `json:"preNodeId,omitempty"`
	// 主体ID
	SubjectId int32 `json:"subjectId,omitempty"`
	// 项目ID
	ProjectId int64 `json:"projectId,omitempty"`
	// 结点名称
	Name string `json:"name,omitempty"`
	// 结点描述
	Desc string `json:"desc,omitempty"`
	// 结点类型
	NodeType string `json:"nodeType,omitempty"`
	// 结点创建时间
	CreateTime string `json:"createTime,omitempty"`
	// 结点修改时间
	UpdateTime string `json:"updateTime,omitempty"`
	// 结点排序位置
	Index int32 `json:"index,omitempty"`
	// 结点层级
	Level int32 `json:"level,omitempty"`
	// 结点所含标签个数
	LabelCount int32 `json:"labelCount,omitempty"`
	// 结点显示标识符
	Display bool `json:"display,omitempty"`
	// 子结点实体列表
	SubNodes []LabelTreeNode `json:"subNodes,omitempty"`
	// 结点所挂载标签实体列表
	LabelInfos []LabelInfo `json:"labelInfos,omitempty"`
}
