/*
 * Copyright 2022 ByteDance and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * CDP开放接口
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2023-02-10
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InsightRecord struct {
	InsightTagName string `json:"insightTagName,omitempty"`
	InsightSegmentation string `json:"insightSegmentation,omitempty"`
	InsightTagValue string `json:"insightTagValue,omitempty"`
	InsightTagCoverage float32 `json:"insightTagCoverage,omitempty"`
	InsightFull int64 `json:"insightFull,omitempty"`
	InsightFullTgi int64 `json:"insightFullTgi,omitempty"`
	InsightEffectiveCoverage float32 `json:"insightEffectiveCoverage,omitempty"`
	InsightTagTgi int64 `json:"insightTagTgi,omitempty"`
	InsightFullTgiLowBound int64 `json:"insightFullTgiLowBound,omitempty"`
	InsightFullTgiUppBound int64 `json:"insightFullTgiUppBound,omitempty"`
	InsightTagTgiLowBound int64 `json:"insightTagTgiLowBound,omitempty"`
	InsightTagTgiUppBound int64 `json:"insightTagTgiUppBound,omitempty"`
	InsightHorizontalTagName string `json:"insightHorizontalTagName,omitempty"`
	InsightHorizontalTagValue string `json:"insightHorizontalTagValue,omitempty"`
	InsightVerticalTagName string `json:"insightVerticalTagName,omitempty"`
	InsightVerticalTagValue string `json:"insightVerticalTagValue,omitempty"`
	InsightTagProportion int64 `json:"insightTagProportion,omitempty"`
}
